### PR TITLE
add correct formats to assignments

### PR DESCRIPTION
**Pull request by hugonugraM**

### CODE REVIEW

**Comment by paoespinozarias** [comment]
Hi Hugo, 

Your assignments are ok. However, I don't understand your last commit where you executed a merge. This last commit modifies other files that are not related to your assignments. Thus, I can't accept your request. 

Did you follow these steps? :
1) Fetch your repository with the recent changes from our repository.
2) Add your assignment files into the corresponding directories.
3) Commit your changes.
4) Send the pull request.

If not, I recommend you make a backup of your assignment files. Then, delete the repository in your GitHub account. After, make a new fork from our repository. Finally, follow the steps that I mentioned before. Also, you can check this [instructions](https://github.com/FacultadInformatica-LinkedData/Curso2019-2020-OpenDataKnowledgeGraphs)

**Comment by hugonugraM** [comment]
What I did before was merging my local repository with the main repository, now I have reseted my repository to the commit before i did the merge.

**Comment by hugonugraM** [comment]
There is a conflict with the first file who should resolve the conflict you or me? @paoespinozarias

**Comment by paoespinozarias** [comment]
No worries, I fixed this last conflict and accepted your request.

**Pull request merged**
