### PR TITLE
Pull request group 10

### PR DESCRIPTION
**Pull request by pablopsoto**

### CODE REVIEW

**Comment by rgcmme** [comment]
- You are updating the self-assessment template. Remove this change from the pull request.
- Check that all property names start with non-capital letter.
- The identifier is not an integer.
- You are defining Date as a class, but later using it as a datatype (which is correct).
- This URIs of the types of individuals are not well written, and they are wrong.
- Verify that the class and property names used in the RDF data are the same as those used in the ontology.
- Add labels to individuals; don't require people to interpret your URIs.

**Comment by pablopsoto** [comment]
Dear Raul, we hope we understood your comments and did the changes correctly. Thank you very much for your help!

**Comment by rgcmme** [comment]
You are still updating the self-assessment template. This causes conflicts, so the pull request cannot be merged directly.
Remove the file from the pull request.

**Comment by pablopsoto** [comment]
I deleted the template folder already and it does not appear any more in my repository but I'm doing something wrong as I don't know how to delete it from the pull request.

**Comment by rgcmme** [comment]
Then maybe the best option is to close this one and create another pull request that only includes the changes that you want.

**Comment by pablopsoto** [comment]
Alright, I'm going to do that then! Thanks

**Comment by pablopsoto** [comment]
I don’t manage to create a new pull request with only the changes that I want. I created a new branch and cherry-pick the latest commit which does not include the template folder but it still does not work for me. I don’t know what can I do.

**Comment by rgcmme** [comment]
I suggest to copy the changes you have made to another place, then to delete your local copy and download everything as is in the repository.
Then, only apply there the changes that you want to make.

**Comment by pablopsoto** [comment]
Exactly that’s what I’m doing now. Let’s see if it works, thanks a lot for
all your help!

**Pull request closed without merging**
