### PR TITLE
Assignment1 done

### PR DESCRIPTION
**Pull request by Znabil**

### CODE REVIEW

**Comment by Znabil** [comment]
i just completed the second assignment feel free to evaluate my work.

**Comment by paoespinozarias** [comment]
Hi Aziz, 

Your Assigment 1 is ok. However I have few comments on your Assignment 2:

- Exercise 1.a is ok.

- Exercise 1.b have some errors: 
a) Your xml:base definition is ok but you are naming in wrong way the resources. For example _#Class01_. This is not necessary to add "#" because you have it defined in you xml:base. But no worries, you will learn how to deal with URI definitions on today's class.
b) _DateTime_ datatype is wrong, the correct name is _dateTime_.  In addition, _Celsius_ doesn't exist in XMLschema definition, the same for _Name._ If you want to define XMLschema datatypes you need to check all those available at specification: https://www.w3.org/TR/xmlschema-2.

- Exercise 1.c have some errors: 
a) You have the same errors in datatypes that I mentioned before. 
b) The benefit of using Turtle serialization is to make data human-readable. For example: Instead of  _<https://github.com/Znabil/Class01#Class01>_ you can define _:Class01_, and you need to define _@base <https://github.com/Znabil/Class01>_

**Comment by Znabil** [comment]
holla I've corrected the second Assignment After I noticed your comment please take care to evaluate my job Again. thank you Again.

**Comment by paoespinozarias** [comment]
Hi Aziz,
Your changes are ok. But, my previous comment a) on Exercise 1.b applies for all resources which contain "#": measurement, sensor, etc. Remember that the URI will be applied to all of them.

**Comment by Znabil** [comment]
I just finished the task 6 and 7 please take care to review my code , I will do the correction you mentioned on the exercise 1.B ; 
best regards.

**Comment by Znabil** [comment]
.

**Comment by paoespinozarias** [comment]
Hi Aziz,

Comments about your tasks:

- The changes in assignment 2 are ok. However, in exercise 1b you are still using _Celsius_ as an XMLschema definition, but it doesn't exist. When you use a standard definition you have to use the datatypes previously defined in the specification. 
- In Taks6:
a) In 6.2 you don't need to create the class Person. You only have to retrieve it from the model because this class is already define in example5.rdf file.
b) In 6.6 the property "_worksIn_" should not be related to the individual _Jane Smith_ . Instead of this, you have to relate it to the individual John Smith, an individual already defined in example5.rdf file. You only have to retrieve it from the model and then relate it with UPM.
c) Task 7.3 is ok. You also can solve it using the inference provided by Jena. Check options for Ont.ModelSpec (RDFS_MEM....) 

Comments about delivering:
- For Assignment 3, you have to create a new folder and only add your task6.java and task7.java files inside your new folder. Please, follow these instructions: _"Before uploading the files create a folder with your YourGitHubID-StudentID (e.g., Assignment3/dchaves/) in Assignment3 folder."_ 

- Please, fix these details in delivering and commit your changes. Take care of not include any other file or edit our original files.

**Pull request closed without merging**
