### PR TITLE
Group02 - Assingment 1 -2 

### PR DESCRIPTION
**Pull request by macvayne**
According instruction of  Raul,  the old pull request were deleted and was created a new one

### CODE REVIEW

**Comment by rgcmme** [comment]
- You are deleting the README file from the root directory. Remove this change from the pull request.
- The ontology is not in the OWL language. Use the Protege tool to make the ontology.

**Comment by macvayne** [comment]
Raul,  how can i remove   change   from the pull request.  Thanks you

**Comment by rgcmme** [comment]
Here you have hints:
https://stackoverflow.com/questions/9498201/delete-file-from-pull-request-on-github/37122300

**Comment by macvayne** [comment]
Will create a new pull Request due of  conflic with readme.md

**Pull request closed without merging**
