### PR TITLE
Assignment-Task06

### PR DESCRIPTION
**Pull request by Ka77y**
Pull request for Task 6 Assignment 3 in Remote repository

### CODE REVIEW

**Comment by paoespinozarias** [comment]
Hi Katherine, 

Your task is ok. However, in example5.rdf file you have already the individual "John Smith", thus, it is not neccesary to create it for task 6.6. You only have to retrieve it from the model and then add the property.

Comments about delivering:
- You have to create a new folder and only add your task6.java file inside your new folder. Please, follow the instructions: _Before uploading the files create a folder with your YourGitHubID (e.g., Assignment3/dchaves) in Assignment3 folder._
- It means that our original file task6.java should not be modified.

**Comment by rgcmme** [comment]
- You are updating one file out of your directory:  Assignment3/src/main/java/upm/oeg/wsld/jena/Task06.java. Remove it from the pull request or move it to the correct directory as Paola mentions.
- Values are not entities that can be linked.
- Leave only the .ttl ontology file, remove the other one.
- Check the datatypes of your datatype properties. For example, identifiers such as postal codes are not numbers.
- Use meaningful names in classes and properties in the ontology.

**Comment by Ka77y** [comment]
Grupo04-ProjectUpdate

**Comment by rgcmme** [comment]
- There are other class and properties that are frequently used and that can be reused from other ontologies or vocabularies.
- The URIs have to follow the resource naming strategy.
- The URI of an individual should be "readable" and have some meaning. An auto-increased integer does not satisfy this.
- Some individuals have no type.
- One property is duplicated: borough and hasBorough.
- The property isLocated has two values. One should be cleaned or removed.
- Datatypes are missing.
- Latitude and longitude are not encoded as literals.
- Not every string with numbers is a number (e.g., zip).
- Not all the links are correct:  <http://www.grupo04.upm.es/new-york-hotspot/resource/resource_type#SPECTRUM> owl:sameAs <https://www.wikidata.org/wiki/Q2961234>

**Pull request merged**
