### PR TITLE
GROUP04 changed dataset and updated the project files

### PR DESCRIPTION
**Pull request by irene057**

### CODE REVIEW

**Comment by irene057** [comment]
submite assigment of group04

**Comment by rgcmme** [comment]
- You are updating the HandsOn/README.md file and many other files outside your group directory. Either clean this pull request or close it and make a new one with only the required changes.
- The values in the dataset are not individuals.
- It is not clear which benefits will be obtained from linking those data with other datasets.
- The name of the ontology file must be ontology and not ontolgy.
- You don't need to import your own ontology.
- What you are defining as object properties are datatype properties. The way of defining the ranges of these properties is not correct.

**Comment by irene057** [comment]
we have change dataset entirely

**Comment by irene057** [comment]
hello we changed the dataset entirely and we updated all  files please take time to review our jobe and give your notes . thanks in advance .
best regards.

**Comment by rgcmme** [comment]
You are still updating plenty of files not related to the hands-on. Should we close this pull request?

**Pull request closed without merging**
